package fuzzer.automwe

import fuzzer.automwe.rules.SubtreePruningRule
import fuzzer.automwe.search.{BestFirstSearchAgent, DeltaDebuggingAgent}
import fuzzer.core.graph.{DFOperator, Graph}
import play.api.libs.json.Json
import fuzzer.utils.generation.dag.DFGSerializer
import java.io.{File, FileWriter}

object AutoMWE {
  /** Produce a minimal working example of some source code generated by the fuzzing campaign */
  def main(args: Array[String]): Unit = {
    val dfgPath = args.headOption
      .getOrElse(throw new IllegalArgumentException("Usage: AutoMWE <path-to.dfg.json>"))

    val (oracle, initialGraph, shutdown) = MinimizationOracle.fromDFGFile(dfgPath)

    try {
      assert(
        oracle.isValidCandidate(initialGraph),
        "Reconstruction Failed: original graph no longer reproduces the fault — cannot minimize."
      )

      val initialCost = oracle.cost(initialGraph)
      println(s"Initial complexity: ${initialCost}")
      println(s"Target result type: ${oracle.originalResult}")

      val rules = Seq(SubtreePruningRule)
      val minimal = BestFirstSearchAgent.minimize(initialGraph, oracle, rules)

      val finalCost = oracle.cost(minimal)
      println(s"\n===== MINIMIZATION RESULTS =====")
      println(s"Original : $initialCost")
      println(s"Minimal  : $finalCost")
      println(s"${initialCost.nodeCount - finalCost.nodeCount} nodes were removed.")

      writeOutput(dfgPath, minimal, oracle)

    } finally {
      shutdown()
    }
  }

  /** Writes the minimized graph and regenerated source alongside the original. */
  private def writeOutput(
    originalPath: String,
    minimal:      Graph[DFOperator],
    oracle:       MinimizationOracle
  ): Unit = {
    val base = originalPath.stripSuffix(".dfg.json")

    // Write minimized DFG JSON
    // val minJson     = new File(base + ".min.dfg.json")
    // val jsonWriter  = new FileWriter(minJson)
    // jsonWriter.write(Json.prettyPrint(
    //   DFGSerializer.serialize(minimal, oracle.originalResult, fuzzer.core.global.State.config.get)
    // ))
    // jsonWriter.close()
    // println(s"Wrote minimized graph: ${minJson.getPath}")

    // Write regenerated source
    val minScala    = new File(base + ".min.scala")
    val scalaWriter = new FileWriter(minScala)
    val source      = oracle.generateSource(minimal)
    scalaWriter.write(source.preamble + "\n\n" + source.src)
    scalaWriter.close()
    println(s"Wrote minimized source: ${minScala.getPath}")
  }
}
